variables:
  MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  MYSQL_ROOT_HOST: "%"
  MYSQL_DATABASE: ${DB_NAME}
  MYSQL_USER: ${DB_USERNAME}
  MYSQL_PASSWORD: ${DB_PASSWORD}
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_NAME: ${DB_NAME}
  DB_PORT: ${DB_PORT}
  DB_HOST: ${DB_HOST}
  DB_TEST_HOST: ${DB_HOST}

before_script:
  - rm -fr /var/www/html
  - test -e /usr/local/etc/php/conf.d && cp ./dev/docker/php/conf.d/custom.ini /usr/local/etc/php/conf.d/custom.ini

stages:
  - build
  - tests
  - dev
  - test
  - live

build_vendor:
  stage: build
  image:
    name: hub.ci.gbksoft.net:5000/pub/php-apache:7.1
    entrypoint: [""]
  artifacts:
    untracked: true
    paths:
      - vendor/
#      - /design/node_modules/
#      - design/dist/
    when: on_success
    expire_in: 2 days
  cache:
    key: vendors-lib
    paths:
      - vendor/
#        - /design/node_modules/
  script:
    - echo "===== Install dependencies ====="
    - chmod +x ./composer-install.sh && ./composer-install.sh
  when: always
  tags:
    - shared-cli

phpmd:
  stage: tests
  image:
    name: hub.ci.gbksoft.net:5000/pub/php-apache:7.1
    entrypoint: [""]
  script:
    - echo "===== Run tests ====="
    - vendor/bin/dep tests:php_md
  when: always
  only:
    - web
  dependencies:
    - build_vendor
  tags:
    - shared-cli

phpcpd:
  stage: tests
  image:
    name: hub.ci.gbksoft.net:5000/pub/php-apache:7.1
    entrypoint: [""]
  script:
    - echo "===== Run tests ====="
    - vendor/bin/dep tests:php_cpd
  when: always
  dependencies:
    - build_vendor
  tags:
    - shared-cli

phpcs:
  stage: tests
  image:
    name: hub.ci.gbksoft.net:5000/pub/php-apache:7.1
    entrypoint: [""]
  script:
    - echo "===== Run tests ====="
    - vendor/bin/dep tests:php_cs
  when: always
  dependencies:
    - build_vendor
  tags:
    - shared-cli

phpsa:
  stage: tests
  image:
    name: hub.ci.gbksoft.net:5000/pub/php-apache:7.1
    entrypoint: [""]
  script:
    - echo "===== Run tests ====="
    - vendor/bin/dep tests:php_sa
  when: always
  dependencies:
    - build_vendor
  tags:
    - shared-cli

codecept:
  stage: tests
  image:
    name: hub.ci.gbksoft.net:5000/pub/php-apache:7.1
    entrypoint: [""]
  services:
    - name: mysql:5.7
      alias: mysql
      command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  artifacts:
    untracked: true
    paths:
      - frontend/tests/
      - backend/tests/
      - common/tests/
      - rest/tests/
    when: on_failure
    expire_in: 2h
  variables:
    DB_TEST_HOST: ${DB_HOST}
    DB_TEST_NAME: ${DB_NAME}
    DB_TEST_PORT: ${DB_PORT}
    PROXY_build_DOMAIN: codecept-${MAIN_DOMAIN}
    YII_MAIN_DOMAIN: codecept-${MAIN_DOMAIN}
    YII_REST_DOMAIN: codecept-${MAIN_DOMAIN}
    YII_BACKEND_DOMAIN: codecept-${MAIN_DOMAIN}
    BUILD_URL: https://codecept-$MAIN_DOMAIN
    YII_BUILD_ENV: Dev
  script:
    - echo "===== All services ====="
    - cat /etc/hosts | grep '10.1.' | awk '{print $1" "$2;}'
    - ./vendor/bin/dep gitlab:deploy
    - /etc/init.d/apache2 start
    - ./vendor/bin/codecept run
  except:
    - master
  environment:
    name: codecept-review/$CI_PROJECT_PATH_SLUG
    url: $BUILD_URL
  when: always
  dependencies:
    - build_vendor
  tags:
    - shared-web

dev:review:
  stage: dev
  when: manual
  image:
    name: hub.ci.gbksoft.net:5000/pub/php-apache:7.1
    entrypoint: [""]
  services:
    - name: mysql:5.7
      alias: mysql
      command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  variables:
    PROXY_build_DOMAIN: dev-${MAIN_DOMAIN}
    YII_MAIN_DOMAIN: dev-${MAIN_DOMAIN}
    YII_REST_DOMAIN: dev-${MAIN_DOMAIN}
    YII_BACKEND_DOMAIN: dev-${MAIN_DOMAIN}
    BUILD_URL: https://dev-$MAIN_DOMAIN
    YII_BUILD_ENV: Dev
  script:
    - echo "===== All services ====="
    - cat /etc/hosts | grep '10.1.' | awk '{print $1" "$2;}'
    - echo "===== Run SSH ====="
    - HOSTIP=`ip addr | grep "global eth0" | awk '{print $2;}' | cut -f 1 -d "/"`
    - echo "ssh ${GITLAB_USER_LOGIN}@${HOSTIP}"
    - echo "SSH Password ${CI_COMMIT_SHA}"
    - sed -ri "s/^sshlogin/${GITLAB_USER_LOGIN}/" /etc/passwd
    - echo "${GITLAB_USER_LOGIN}:${CI_COMMIT_SHA}" | chpasswd
    - mkdir /var/run/sshd && /usr/sbin/sshd -f /etc/ssh/sshd_config

    - ./vendor/bin/dep gitlab:deploy
    - apache2-foreground
  only:
    - web
  except:
    - master
  environment:
    name: dev-review/$CI_PROJECT_PATH_SLUG
    url: $BUILD_URL
  dependencies:
    - build_vendor
  tags:
    - shared-web

dev:swagger:
  stage: dev
  when: manual
  image:
    name: hub.ci.gbksoft.net:5000/pub/swagger:3
  variables:
    PROXY_build_HTTPS: "443:8080"
    PROXY_build_DOMAIN: dev-swagger-ui-${MAIN_DOMAIN}
    BUILD_URL: https://dev-swagger-ui-${MAIN_DOMAIN}
    API_URL: "https://dev-$MAIN_DOMAIN/rest/swagger/main/json"
  script:
    - echo "===== Run Swagger UI ====="
    - echo "Swagger UI URL ${BUILD_URL}"
    - echo "JSON URL ${API_URL}"
    - sh /usr/share/nginx/docker-run.sh
  only:
    - web
  except:
    - master
  environment:
    name: dev-swagger-ui/$CI_PROJECT_PATH_SLUG
    url: $BUILD_URL
  tags:
  - shared-web

test:review:
  stage: test
  when: manual
  image:
    name: hub.ci.gbksoft.net:5000/pub/php-apache:7.1
    entrypoint: [""]
  services:
    - name: mysql:5.7
      alias: mysql
      command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  variables:
    PROXY_build_DOMAIN: test-${MAIN_DOMAIN}
    YII_MAIN_DOMAIN: test-${MAIN_DOMAIN}
    YII_REST_DOMAIN: test-${MAIN_DOMAIN}
    YII_BACKEND_DOMAIN: test-${MAIN_DOMAIN}
    BUILD_URL: https://test-$MAIN_DOMAIN
    YII_BUILD_ENV: Test
  script:
    - echo "===== All services ====="
    - cat /etc/hosts | grep '10.1.' | awk '{print $1" "$2;}'
    - export DB_IP=`cat /etc/hosts | grep "${DB_HOST}" | awk '{print$1;}'`
    - echo "===== Run SSH ====="
    - HOSTIP=`ip addr | grep "global eth0" | awk '{print $2;}' | cut -f 1 -d "/"`
    - echo "ssh ${GITLAB_USER_LOGIN}@${HOSTIP}"
    - echo "SSH Password ${CI_COMMIT_SHA}"
    - sed -ri "s/^sshlogin/${GITLAB_USER_LOGIN}/" /etc/passwd
    - echo "${GITLAB_USER_LOGIN}:${CI_COMMIT_SHA}" | chpasswd
    - mkdir /var/run/sshd && /usr/sbin/sshd -f /etc/ssh/sshd_config

    - ./vendor/bin/dep external_config --db_ip=${DB_IP} --var_name=DB_IP --token=${GITLAB_TOKEN} --project=$CI_PROJECT_ID
    - ./vendor/bin/dep gitlab:deploy
    - apache2-foreground
  only:
    - web
  except:
    - master
  environment:
    name: test-review/$CI_PROJECT_PATH_SLUG
    url: $BUILD_URL
  dependencies:
    - build_vendor
  tags:
    - shared-web

test:swagger:
  stage: test
  when: manual
  image:
    name: hub.ci.gbksoft.net:5000/pub/swagger:3
  variables:
    PROXY_build_HTTPS: "443:8080"
    PROXY_build_DOMAIN: test-swagger-ui-${MAIN_DOMAIN}
    BUILD_URL: https://test-swagger-ui-${MAIN_DOMAIN}
    API_URL: "https://test-$MAIN_DOMAIN/rest/swagger/main/json"
  script:
  - echo "===== Run Swagger UI ====="
  - echo "Swagger UI URL ${BUILD_URL}"
  - echo "JSON URL ${API_URL}"
  - sh /usr/share/nginx/docker-run.sh
  only:
    - web
  except:
    - master
  environment:
    name: test-swagger-ui/$CI_PROJECT_PATH_SLUG
    url: $BUILD_URL
  tags:
  - shared-web

live:review:
  stage: live
  when: manual
  image:
    name: hub.ci.gbksoft.net:5000/pub/php-apache:7.1
    entrypoint: [""]
  services:
    - name: mysql:5.7
      alias: mysql
      command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  variables:
    PROXY_build_DOMAIN: live-${MAIN_DOMAIN}
    YII_MAIN_DOMAIN: live-${MAIN_DOMAIN}
    YII_REST_DOMAIN: live-${MAIN_DOMAIN}
    YII_BACKEND_DOMAIN: live-${MAIN_DOMAIN}
    BUILD_URL: https://live-$MAIN_DOMAIN
    YII_BUILD_ENV: Live
  script:
    - echo "===== All services ====="
    - cat /etc/hosts | grep '10.1.' | awk '{print $1" "$2;}'
    - echo "===== Run SSH ====="
    - HOSTIP=`ip addr | grep "global eth0" | awk '{print $2;}' | cut -f 1 -d "/"`
    - echo "ssh ${GITLAB_USER_LOGIN}@${HOSTIP}"
    - echo "SSH Password ${CI_COMMIT_SHA}"
    - sed -ri "s/^sshlogin/${GITLAB_USER_LOGIN}/" /etc/passwd
    - echo "${GITLAB_USER_LOGIN}:${CI_COMMIT_SHA}" | chpasswd
    - mkdir /var/run/sshd && /usr/sbin/sshd -f /etc/ssh/sshd_config

    - composer install --no-interaction --optimize-autoloader --no-progress --no-dev
    - ./vendor/bin/dep gitlab:deploy
    - apache2-foreground
  only:
    - master
  environment:
    name: live-review/$CI_PROJECT_PATH_SLUG
    url: $BUILD_URL
  tags:
    - shared-web
