version: '3.3'
services:
  web-php:
    image: hub.ci.gbksoft.net:5000/pub/php-apache:7.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./dev/docker/apache2/php/etc/cmd/entrypoint.sh:/entrypoint.sh
      - ./dev/docker/apache2/php/etc/ssl:/etc/apache2/ssl
      - ./dev/docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/html
    environment:
      # Custom user ID and group ID to start
      # Get auto if not set
      DCUID: ${DCUID}
      DCGID: ${DCGID}
      MAIN_DOMAIN: ${MAIN_DOMAIN}
      DESIGN_REPO_URL: ${DESIGN_REPO_URL}
      YII_BUILD_ENV: "Dev"
      YII_MAIN_DOMAIN: ${MAIN_DOMAIN}
      YII_REST_DOMAIN: ${REST_DOMAIN}
      YII_BACKEND_DOMAIN: ${BACKEND_DOMAIN}
      GITHUB_KEY: ${GITHUB_KEY}
      PHP_IDE_CONFIG: "serverName=${MAIN_DOMAIN}"
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_autostart=0 remote_connect_back=0 remote_enable=1 remote_mode=req remote_host=${XDEBUG_HOST}"
    links:
      - db
      - dbtest
  db:
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./dev/docker/mysql/5.7/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
  dbtest:
    image: mysql:5.7
    ports:
      - "${DB_TEST_PORT}:3306"
    volumes:
      - ./dev/docker/mysql/5.7/test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_TEST_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
  swagger-ui:
    image: hub.ci.gbksoft.net:5000/pub/swagger-ui:latest
    environment:
      API_URL: "https://${REST_DOMAIN}/rest/swagger/main/json"
    ports:
      - "8080:8080"
