version: '3.3'
services:
  web-php:
    image: hub.ci.gbksoft.net:5000/pub/php-apache:7.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./dev/docker/apache2/php7.1/etc/cmd/entrypoint.sh:/entrypoint.sh
      - ./dev/docker/apache2/php7.1/etc/ssl:/etc/apache2/ssl
    working_dir: /var/www/html
    environment:
      # Custom user ID and group ID to start
      # Get auto if not set
#      DCUID: ${DCUID}
#      DCGID: ${DCGID}
      MAIN_DOMAIN: ${MAIN_DOMAIN}
      YII_BUILD_ENV: "Dev"
      GITHUB_KEY: ${GITHUB_KEY}
      PHP_IDE_CONFIG: "serverName=hostname.loc"
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      # !!! Set your IP 10.0.75.1
      # !!! Set your PORT 9123
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_autostart=0 remote_connect_back=0 remote_enable=1 remote_mode=req remote_port=9123 remote_host=10.0.75.1"
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./dev/docker/mysql/5.7/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
